spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #로딩 시점에, 테이블을 드랍 후 다시 생성함, 운영할 땐 사용하면 안됨
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com #SMTP 서버 호스트
    port: 587 #SMTP 서버 포트
    username: gusdldi300 #SMTP 서버 로그인 아이디
    password: awxftjrmlfxripyx #SMTP 서버 로그인 패스워드
    properties:
      mail:
        smtp:
          auth: true #사용자 인증 시도 여부
          timeout: 5000 #Socket Read Timeout 시간(ms)
          starttls:
            enable: true #StartTls 활성화 여부


logging.level:
  org.hibernate.SQL: debug #로그를 파일로 남김
# org.hibernate.type: trace